- src/Command/AbstractCommand.php
@Narno requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/PHPoole/PHPoole/
> Scrutinizer Auto-Fixes

- src/Command/AbstractCommand.php
- src/Command/Build.php
- src/Command/ListContent.php
- src/Command/NewWebsite.php
- src/Command/Serve.php
- exceptions handling
- fix draft option
- and more
> Improvements

- composer.json
- composer.lock
- config/routes.php
- src/Command/AbstractCommand.php
- src/Command/Build.php
- quiet mode = not verbose
- phpoole/library 2.3.0
- debug mode
- dedicated error messages
> Quiet mode.

- composer.json
- composer.lock
- config/routes.php
- src/Command/Build.php
- src/Command/Config.php
- src/Command/NewPage.php
- src/Command/NewWebsite.php
- src/Command/Serve.php
New commands:
- `newpage <name> [<path>] [--force|-f]`: create a new page `<name>.md`
- `config [<path>]`: display website configuration
- `build --remove`: remove output directory (ie: `_site`)
- `serve --clear`: clear temporary files created by server (`.phpoole`)
> New commands! \o/

- src/Command/NewPage.php
An Archetype is a page model.
When you create a new page with `phpoole newpage` command, you can specify the file path like `blog/new-post`.
In this case, PHPoole will search for a model file in `archetypes` directory and use it if exist.
In our previous example it will search `archetypes/blog.md` file and use its content to create your new page.
> [WIP] Archetypes feature.

- src/Collection/Item.php
- src/Collection/Page/Page.php
- src/Converter/Converter.php
- src/Converter/Parsedown.php
- src/Generator/VirtualPages.php
- src/Renderer/Twig/Extension.php
https://scrutinizer-ci.com/g/Cecilapp/Cecil/inspections/dbabe373-8883-46b0-8236-f58e5df3103d/issues/
> Code Style

- .github/workflows/deploy.yml
- .github/workflows/docs.yml
- .github/workflows/test.yml
- .travis.yml
- composer.json
- composer.lock
- scripts/deploy-dist.sh
> Move CI pipeline to GitHub Actions

- composer.lock
- docs/3.Templates.md
- resources/layouts/partials/languages.html.twig
- src/Assets/Url.php
- src/Builder.php
- src/Collection/Page/Page.php
- src/Config.php
- src/Generator/Section.php
- src/Renderer/Site.php
- src/Step/MenusCreate.php
- tests/fixtures/website/config.php
- tests/fixtures/website/content/Others/intl.fr.md
This is a major PR that introduce translation of Menus, Sections and `url()` function.
> feature: localizes Menus, Sections and url()

- resources/layouts/partials/alternateslang.html.twig
- resources/layouts/partials/metatags.html.twig
- resources/layouts/sitemap.xml.twig
1. https://developers.google.com/search/docs/advanced/crawling/localized-versions
2. https://en.wikipedia.org/wiki/Hreflang
> feature: add `hreflang` to HTTP tags and Sitemap

- docs/3.Templates.md
- resources/layouts/_default/list.html.twig
- resources/layouts/_default/list.json.twig
- resources/layouts/feed.twig
- resources/layouts/sitemap.xml.twig
- src/Collection/Page/Collection.php
- src/Renderer/Site.php
- `site.pages`: Collection of pages, in the current language
- `site.pages.showable`: `site.pages` with "showable" pages only (published, not virtual/redirect/excluded)
- `site.allpages`: Collection of pages, regardless of their translation.
> feature: enhances access to all pages

- config/default.php
- docs/4-Configuration.md
- src/Assets/Asset.php
- src/Assets/Image.php
- src/Step/PostProcess/Images.php
```yaml
assets:
images:
optimize:
enabled: true # Optimizes images with JpegOptim, Optipng, Pngquant 2, SVGO 1, Gifsicle (`false` by default)
quality: 85
```
> feature: optimize image asset automatically

- composer.lock
- config/default.php
- docs/4-Configuration.md
- src/Assets/Asset.php
- src/Assets/Image.php
- src/Converter/Parsedown.php
- src/Renderer/Twig/Extension.php
- feature: auto adds `srcset` attribute to images created with `html` filter
- feature: auto adds `width` and `height` attributes to images created with `html` filter
- fix: `resize` filter should not process if `$size` is bigger than image width
- chore: enhances code quality
> feature: responsives images in templates with `html` filter

- docs/5-Commands.md
- src/Command/NewPage.php
- fix model finder
- fix the way to open the file with an editor on Windows
> fix: `new:page` command

- src/Builder.php
- src/Command/Build.php
- src/Command/Serve.php
- src/Step/Content/Load.php
> feat: build a specific page

- config/default.php
- docs/4-Configuration.md
- src/Step/Content/Load.php
```yaml
content:
dir: content
ext: [md]
exclude: [dir1, '*.ext'] # list of excluded files (accepts globs, strings and regexes)
```
> feat: exclude dir/path/files in content

- docs/3-Templates.md
- src/Renderer/Twig/Extension.php
- tests/fixtures/website/assets/yaml.yml
- tests/fixtures/website/layouts/filters.html.twig
```twig
{{ yaml|yaml_parse }}
```
> feat: template filter `yaml_parse`

- src/Step/Menus/Create.php
Fix URL of the 404 page in case of error in the URL of a localized menu entry.
> fix: 404 URL menu localisation

- composer.json
- src/Command/AbstractCommand.php
- src/Command/Build.php
- src/Command/NewPage.php
> fix: can't create a new page

- resources/layouts/_default/page.html.twig
- Fix missing end tag for the main element
> fix: end tag for main element

- docs/4-Configuration.md
- resources/layouts/feed.twig
- src/Collection/Page/Page.php
- src/Generator/AbstractGenerator.php
- src/Generator/Alias.php
- src/Generator/Homepage.php
- src/Generator/Pagination.php
- src/Generator/Section.php
- src/Generator/Taxonomy.php
- src/Generator/VirtualPages.php
- src/Renderer/Page.php
- src/Renderer/Site.php
- src/Step/Menus/Create.php
- src/Step/Pages/Convert.php
- src/Step/Pages/Create.php
- src/Step/Pages/Render.php
- src/Step/Pages/Save.php
- src/Util/Str.php
Do not store "complex" objects like pages collections or rendered content in a page variable.
> Recode page variables handling

- resources/layouts/partials/data.json.twig
- src/Collection/Page/Page.php
- src/Generator/Homepage.php
Generated home page (list of all pages) is now filtered by language.
> feat: support of i18n for homepage

- src/Builder.php
- src/Collection/Page/PrefixSuffix.php
- src/Config.php
Checks if:
1. default language is valid
2. locale of each language is valid
> feat: check of language and locale configuration

- src/Renderer/Twig.php
> fix(intl): set locale only if Intl ext is loaded

- src/Builder.php
- src/Util.php
Example:
```bash
php cecil build -v
Building website...
Path: /website
Config: /website/config.yml
Cache: /website/.cache
1. Importing themes configuration
2. Loading pages
3. Creating pages
4. Converting pages
5. Creating taxonomies
6. Generating pages
7. Creating menus
8. Copying static
9. Rendering pages
10. Saving pages
Built in 14 s (19.67 mb)
````
> feat: print memory usage in verbose mode

- docs/3-Templates.md
- docs/5-Commands.md
- src/Application.php
- src/Command/UtilExtractTemplates.php
- src/Util/Plateform.php
Extracts built-in templates in the "layouts" directory of your site.
Usage:
```bash
php cecil.phar util:extract
```
> feat: new command to extract templates

- docs/3-Templates.md
- resources/layouts/_default/list.atom.twig
- resources/layouts/extended/feed.twig
- src/Assets/Url.php
Example:
```twig
{{ url('page-id', {'language': 'fr'}) }}
```
> feat: add 'language' option to Twig url()

- docs/2-Content.md
- docs/3-Templates.md
- src/Collection/Page/Collection.php
- src/Generator/Section.php
- src/Renderer/Twig/Extension.php
```yaml
---
sortby: date
---
```
```yaml
---
sortby:
variable: date    # date, updated, title or weight
desc_title: false # used with date or updated variables to sort by desc title order if items have same date
reverse: false    # reversed if true
---
```
> feat: options for `sortby` front matter variable

- config/default.php
- docs/3-Templates.md
- docs/4-Configuration.md
- src/Renderer/Extension/Core.php
- tests/fixtures/website/layouts/excerpt_html.html.twig
- tests/fixtures/website/pages/Others/Excerpt HTML.md
Co-Authored-By: Matthieu <14790414+matthieu2607@users.noreply.github.com>
> fix: `excerpt_html` filter options handling

- src/Converter/Parsedown.php
```markdown
[Cecil build script](https://gist.github.com/ArnaudLigny/6b2aa9e6b25581c96435e9296efe0c0e)
```
> feat: embed GitHub Gist link

- config/default.php
- docs/2-Content.md
- docs/4-Configuration.md
- src/Converter/Parsedown.php
```markdown
[The video](/video/test.mp4){controls poster=/images/video-test.png style="width:100%;"}
```
->
```html
<video src="/video/test.mp4" controls poster="/images/video-test.png" style="width:100%;"></video>
```
> feat: turn a link into a video or audio element

- src/Assets/Cache.php
- src/Command/Build.php
```bash
php cecil build -v --clear-cache="^styles.*"
```
> feat: remove cache files by regular expression

- bin/cecil
Fixes issue #1583
**Changes proposed in this pull request:**
Adding runtime checks for required php extension in order to have Cecil working correct
> Fixes #1583 - Enforcing runtime checks for required php extensions

- config/default.php
- docs/4-Configuration.md
- src/Assets/Asset.php
```yaml
assets:
images:
cdn:
enabled: true
url: 'https://res.cloudinary.com/%account%/image/fetch/c_limit,w_%width%,q_%quality%,f_%format%,d_%default%/%image_url%'
account: 'xxxx'
url: 'https://%account%.cloudimg.io/%image_url%?w=%width%&q=%quality%&force_format=%format%'
account: 'xxxx'
```
> feat: add images CDN support

- config/default.php
- src/Assets/Asset.php
- disable custom default image for Cloudinary
- dedicated build URL function
- checks if the targeted image is a SVG
> fix: enhance CDN

- config/default.php
- src/Assets/Asset.php
- Less asset procesing by Cecil (resize and format conversion)
- More options :
- handle remote images
- disable canonical URL
> fix: enhances CDN

- docs/3-Templates.md
- src/Renderer/Extension/Core.php
```twig
{{ asset|webp }}
{{ image_srcset(asset) }}
{{ image_sizes(class) }}
```
```twig
<picture>
<source type="image/webp" srcset="{{ image_srcset(asset|webp) }}" sizes="{{ image_sizes('photo') }}">
</picture>
```
> feat: images functions and filters

- docs/3-Templates.md
- src/Renderer/Layout.php
- src/Step/Taxonomies/Create.php
Fixe #1669.
```
taxonomy/<singular>.<format>.twig
```
> feat: new taxonomy template lookup rule

- composer.json
- composer.lock
- src/Assets/Asset.php
Get MP4 file properties:
- {{ asset.video.width }}
- {{ asset.video.height }}
> feat: Get MP4 properties with `asset.video`

- config/default.php
- resources/layouts/_default/page.iframe.twig
- resources/layouts/_default/page.oembed.twig
- resources/layouts/partials/metatags.html.twig
**_page_.md:**
```yaml
---
videos:
- path/to/mp4
output: [html, iframe, oembed]
---
```
> feat: video formats and embed layouts

- resources/server/router.php
- https://huntr.dev/bounties/d2a9ec4d-1b4b-470b-87da-ec069f5925ae/
- https://huntr.dev/bounties/cdd995b2-c983-428b-a73a-827b61b7c06b/
> Fix security issues

- src/Assets/Image.php
- src/Converter/Parsedown.php
1. adds source image to `srcset` only if its with is minor than the max with of allowed widths
2. if responsive option is enabled, image is resized to the max with of allowed widths
> feat: better responsive image handling

- docs/3-Templates.md
- src/Renderer/Site.php
```twig
Is debug mode: {{ site.debug }}
```
> feat: new `site.debug` variable

- src/Generator/Taxonomy.php
`/pages/<plural>/index.md`:
```yaml
---
title: Custom title
---
```
> feat: customize the title of a taxonomy terms list page

- config/default.php
- docs/2-Content.md
- docs/4-Configuration.md
- src/Collection/Page/Collection.php
- src/Generator/Homepage.php
- src/Generator/Section.php
_config.yml_:
```yaml
pages:
sortby: date
```
> feat: config to define a default sort method

- src/Converter/Parsedown.php
- src/Renderer/Extension/Core.php
- tests/fixtures/website/layouts/markdown-filter.html.twig
- tests/fixtures/website/pages/Markdown/filter.md
Fix update of ParsedownToc from version 1.4.x to 1.5.x.
> fix: parsedown toc

- config/base.php
- config/default.php
- src/Assets/Asset.php
- src/Builder.php
- src/Command/AbstractCommand.php
- src/Config.php
- src/Converter/Parsedown.php
- src/Generator/Pagination.php
- src/Renderer/Extension/Core.php
- src/Renderer/Twig.php
- src/Step/Optimize/Images.php
- src/Step/Pages/Convert.php
- src/Step/Pages/Render.php
- src/Step/Themes/Import.php
Better handling of base and default configuration.
> refactor: rebuild configuration

- docs/4-Configuration.md
- src/Step/StaticFiles/Copy.php
- tests/fixtures/website/config.php
Discussion with @ArnaudLigny  : https://piaille.fr/@arnaud@gazuji.com/113912436712295102
* Support for mounts points in static configuration
> Support for mounts points in static configuration

- docs/7-Extend.md
- resources/layouts/_default/page.html.twig
- resources/layouts/_default/page.iframe.twig
- resources/layouts/_default/redirect.html.twig
- resources/layouts/partials/alternates-languages.html.twig
- resources/layouts/partials/alternates.html.twig
- resources/layouts/partials/metatags.html.twig
- src/Converter/Parsedown.php
- src/Renderer/Extension/Core.php
- src/Renderer/PostProcessor/GeneratorMetaTag.php
- tests/fixtures/website/extensions/Cecil/Renderer/PostProcessor/Test.php
- tests/fixtures/website/layouts/assets.html.twig
- tests/fixtures/website/layouts/intl.html.twig
- tests/fixtures/website/layouts/section/episodes.rss.twig
- tests/fixtures/website/layouts/static.html.twig
- tests/fixtures/website/layouts/video.html.twig
> refactor: W3C markup validation (XHTML to HTML)

- src/Step/Pages/Render.php
In debug mode, Twig profile is stored in `.debug/`.
> refactor: better Twig profile

- docs/5-Commands.md
- src/Command/Serve.php
* Serve Command : Define the timeout
> Serve Command : Define the timeout

- .github/workflows/documentation.yml
- docs/5-Commands.md
- src/Command/Serve.php
- tests/IntegrationTests.php
* Serve Command : Added metrics option
> Serve Command : Added metrics option

- docs/5-Commands.md
- src/Command/Build.php
- src/Command/Serve.php
```bash
php cecil.phar build --no-optimize
```
> feat: disable build optimization with "--no-optimize" option

- docs/5-Commands.md
- src/Command/NewPage.php
```bash
php cecil.phar new:page --slugify
```
> feat: new:page --slugify

- docs/3-Templates.md
- resources/layouts/partials/metatags.html.twig
- src/Assets/Asset.php
- src/Assets/Image.php
- src/Renderer/Extension/Core.php
Resizes an image to a specified width and height, cropping it if necessary.
```twig
{{ asset(image_path)|cover(width, height) }}
```
> feat: image cover (resize and crop)

- docs/5-Commands.md
- src/Command/Serve.php
```bash
php cecil.phar serve --no-watch
```
> feat: option to disable server watcher

- docs/4-Configuration.md
- resources/layouts/_default/robots.txt.twig
pages/robots.md:
```yaml
---
layout: robots
output: txt
---
User-agent: Example-bot
Disallow: /
```
> feat: add custom rules to robots.txt
