src/Command/Serve.php
Fixes #321.
Changes to templates were not applied after a rebuild when using the "serve" command. The cause is Twig's internal template caching that does not refresh as the rebuild command is running in the same process that created the cache.
As no public Twig API is available to refresh the cache this fix uses a separate process for rebuilding.
- Use PhpExecutableFinder
- Use separate process for running build command to fix templates updates
@Narno please review :eyes:
=> Fix "serve" command not applying template changes

src/Command/NewPage.php
`[ERROR] Expected date format (ie: "2012-10-08") for "date" in .... instead of "2021-02-23""`
Changes proprosed in this pull request:
- Fix single quote causing error
@Narno please review :eyes:
=> Fix single quote causing error

docs/4-Configuration.md, resources/layouts/partials/metatags.html.twig
```yaml
metatags:
favicon:
enabled: true
image: 'favicon.png'
sizes:
- 'icon': [32, 57, 76, 96, 128, 192, 228]
- 'shortcut icon': [196]
- 'apple-touch-icon': [120, 152, 180]
```
=> feature: add favicon with multiple sizes

config/default.php, docs/4-Configuration.md, src/Assets/Asset.php, src/Config.php, src/Step/StaticFiles/Copy.php
**You should** put your assets files, used by `asset()`, in `assets` directory to avoid unnecessary files copy.
```yaml
assets:
dir: assets
```
=> feature: dedicated directory for assets

src/Command/AbstractCommand.php, src/Command/Build.php, src/Command/Serve.php
Multiple configuration files can be specified as a comma-separated string to the `--config` option:
```bash
cecil build --config=config_base.yml,config_production.yml
```
Each entry in a file replaces the one in the previous one if it exists.
=> feature: multiple configuration files

src/Renderer/Twig/Extension.php
- separator: string to use as separator
- capture: string to capture, 'before' (default) or 'after'
=> feature: add options to excerpt filter

config/default.php, docs/2-Content.md, docs/3-Templates.md, docs/4-Configuration.md, src/Converter/Parsedown.php
```markdown
:::tip
**Tip:** Advice here.
:::
```
Is converted to:
```html
<div class="note note-tip">
<p>
<strong>Tip:</strong> Advice here.
</p>
</div>
```
=> feat: Markdown Note block-level element

config/default.php, docs/4-Configuration.md, src/Assets/Image.php, src/Converter/Parsedown.php, src/Renderer/Twig/Extension.php
Responsive images widths now defined by a list:
```yaml
assets:
images:
responsive:
enabled: false
widths: [480, 640, 768, 1024, 1366, 1600, 1920]
```
=> feat: Define responsive images widths

src/Step/StaticFiles/Copy.php
The static files copy step use Symfony Finder that ignore "dot files" by default. This fix that behavior.
=> fix: do not ignore dot files

config/default.php, docs/3-Templates.md, docs/4-Configuration.md, docs/5-Commands.md, src/Application.php, src/Command/CacheClearTemplates.php, src/Command/CacheClearTranslations.php, src/Command/OpenWith.php, src/Config.php, src/Renderer/Twig.php
- feat: config option to define translations dir
- feat: config option to disable translations cache
- feat: new comand to clear translations cache
- fix: create a default translator to always support `trans`
=> feat: translations config + clear cache cmd

docs/4-Configuration.md, src/Generator/Section.php, src/Renderer/Layout.php, src/Step/Pages/Convert.php
Section's pages (i.e.: `section/index.md`) now support custom `path` (set in front matter).
And custom `path` of pages' section can be different by language:
```yaml
paths:
- section: <section’s name>
language: <language> # optional
path: <path of pages, with palceholders>
```
=> feat: support of custom (localized) `path` for section

docs/3-Templates.md, src/Generator/Section.php, src/Step/Pages/Render.php
Variables `page.prev` and `page.next` now contains the page item, so it's easier to access of all properties of the page.
For example:
```twig
<a href="{{ url(page.prev) }}">{{ page.prev.title }}</a>
```
=> feat: enhance prev/next navigation in section

config/default.php, docs/3-Templates.md, docs/4-Configuration.md, src/Renderer/Twig.php
```yaml
translations:
dir: translations       # translations directory
formats: ['yaml', 'mo'] # translations files format (`yaml` and `mo` by default)
```
=> feat: support multiple formats translation

docs/3-Templates.md, src/Converter/Parsedown.php, src/Renderer/Twig/Extension.php
Extracts table of content from a Markdown string, in the given format ("html" or "json", "html" by default).
```twig
{{ page.body|toc }}
{{ page.body|toc('html') }}
{{ page.body|toc('json') }}
```
=> feat: new "toc" filter

docs/3-Templates.md, src/Assets/Image.php, src/Renderer/Twig/Extension.php, tests/fixtures/website/layouts/assets.html.twig
```twig
{{ asset(image_path)|dominant_color }}
```
```
#F2D07F
```
=> feat: fetch the dominant color of an image

composer.lock, src/Converter/Parsedown.php
Example:
```markdown
```
```html
<figure>
<figcaption>Photo about <a href="https://cecil.app">Cecil</a></figcaption>
</figure>
```
=> feat: support of Markdown in `figcaption` (title) of an image

config/default.php, docs/4-Configuration.md, src/Assets/Asset.php, src/Converter/Parsedown.php
```yaml
body:
images:
remote:
enabled: true
fallback:
enabled: true # enables a fallback if image is not found (`false` by default)
path: 'images/no-image.png' # path to the fallback image, stored in assets dir (`` by default)
```
=> feat: local fallback for remote images

docs/2-Content.md, src/Converter/Parsedown.php
Example:
```markdown
[split-testing](https://www.youtube.com/watch?v=5VgpJJUOng4){embed=false}
```
=> fix: disable embed link on demand

resources/server/router.php
Fixes issue #1673 
Wrap live reload script in `<script>...</script>` tags when faced with a missing `</body>`
=> fix: Added script tags to live reload script

docs/3-Templates.md, src/Generator/Pagination.php
New variable `page.paginator.links.path` added: Page ID without position.
Usage example:
```twig
{% if page.paginator %}
<div>
{% for paginator_index in 1..page.paginator.count %}
{% if paginator_index != page.paginator.current %}
{% if paginator_index == 1 %}
<a href="{{ url(pagination.links.first) }}">{{ paginator_index }}</a>
{% else %}
<a href="{{ url(page.paginator.links.path ~ '/' ~ paginator_index) }}">{{ paginator_index }}</a>
{% endif %}
{% else %}
{{ paginator_index }}
{% endif %}
{% endfor %}
</div>
{% endif %}
```
=> feat: enhances pagination

src/Assets/Url.php, src/Collection/Page/Page.php, src/Generator/Alias.php, src/Generator/Homepage.php, src/Generator/Pagination.php, src/Generator/Section.php, src/Generator/VirtualPages.php, src/Renderer/Site.php, src/Step/Menus/Create.php
The way to define a page ID have been refactored: the language code of a translated page is no more a suffix (`page.code`) and is now a prefix (`code/page`).
Example: `blog/post-1.fr` -> `fr/blog/post-1`.
=> refactor: ID of localized pages

config/default.php, docs/4-Configuration.md, src/Builder.php, src/Config.php, src/Generator/Homepage.php, src/Generator/Pagination.php, src/Renderer/Page.php, src/Step/Pages/Save.php
New option to "force" main language code as prefix in pages path:
```yaml
#language: en
language:
code: en
prefix: true
```
=> feat: enable pages path prefix for the main language

src/Renderer/Extension/Core.php
```twig
{{ asset('asset')|html({attr: ''}) }}   # attr=""
{{ asset('asset')|html({attr: '0'}) }}  # attr="0"
{{ asset('asset')|html({attr: null}) }} # attr
```
=> fix: empty attribute in html filter

src/Renderer/Extension/Core.php
Previously, images widths (simple array) were passed to Image::getSizes instead of images sizes (associative array), which were leading always to default sizes array.
=> fix: Core::imageSizes method

src/Command/Serve.php
- The PHP server errors are now logged in `.cecil/errors.log`
- Cecil checks if the host is available when the server is running
- If the PHP server process exit with a code > 0 the error output is printed
- The PHP server process command line is now printed in debug mode
=> feat: better `serve` command feedback

src/Command/Serve.php
=> fix: serve command with PHP bin path with space(s)

config/default.php, docs/2-Content.md, docs/3-Templates.md, docs/4-Configuration.md, src/Assets/Asset.php, src/Assets/Image.php, src/Converter/Parsedown.php, src/Renderer/Extension/Core.php, tests/fixtures/website/config.php
- breaking change: `webp` boolean options have been repalce by `formats`, an array list of alternatives image formats (ie: "avif", "webp")
- new `avif` method to convert an image asset to AVIF format. ie: `{{ asset.avif }}`
- new `avif` filter to convert an image to AVIF format. ie: `{{ asset|avif }}`
- disable "interlaced" by default
- fix dominant color method and, BC, return RGB instead of hexadecimal value
=> feat: multiple image formats support (webp, avif)

composer.lock, docs/4-Configuration.md, resources/server/router.php, src/Command/Serve.php
This feature provide a new configuration structure to define custom HTTP headers, used by the local preview server.
It's useful to test custom Content Security or Cache Policy.
Structure:
```yaml
headers:
- source: <path prefixed with a slash>
headers:
- key: <key>
value: "<value>"
```
_Example:_
```yaml
headers:
- source: /*
headers:
- key: X-Frame-Options
value: "SAMEORIGIN"
- key: X-XSS-Protection
value: "1; mode=block"
- key: X-Content-Type-Options
value: "nosniff"
- key: Content-Security-Policy
value: "default-src 'self'; object-src 'self'; img-src 'self'"
- key: Strict-Transport-Security
value: "max-age=31536000; includeSubDomains; preload"
- source: /images/*
headers:
- key: Cache-Control
value: "public, max-age=31536000"
- source: /assets/*
headers:
- key: Cache-Control
value: …
```
=> feat: custom headers

docs/3-Templates.md, docs/5-Commands.md
Fixes issue # N/A
Cecil's documentation references a non-existing `util:extract` command in pages _Templates_ and _Commands_, I assume this was previously the name for the now named `util:templates:extract` command, both references are updated in this PR.
PS: I read the contributing guide but since this is a documentation change I assumed it wasn't necessary to create an issue first, if my assumption was incorrect I'd be happy to resubmit after first creating an issue.
=> doc: update references to now missing command util:extract

docs/4-Configuration.md, resources/layouts/partials/metatags.html.twig
Config:
```yaml
social:
mastodon:
creator: "@arnaud@gazuji.com"
url: https://gazuji.com/@arnaud
```
Output:
```html
<link rel="me" href="https://gazuji.com/@arnaud" />
<meta name="fediverse:creator" content="@arnaud@gazuji.com">
```
=> feat: add `fediverse:creator` meta support

composer.json, composer.lock, config/default.php, docs/3-Templates.md, src/Renderer/Twig.php, tests/fixtures/website/layouts/components.html.twig, tests/fixtures/website/layouts/components/button.twig, tests/fixtures/website/pages/Others/Components.md
Integrating https://github.com/giorgiopogliani/twig-components extension.
=> feat: Add support of Twig components extension

src/Builder.php, src/Command/Build.php
Add a command option `--metrics` to show some metrics (duration and memory usage) of each step of the build:
```bash
cecil build --metrics
```
=> feat: cmd options to display build steps metrics

src/Assets/Asset.php
Remove duplicated `/thumbnails/<width>` in path of responsive images (resized from a resized image).
=> refactor: fix thumb path

resources/server/router.php, src/Command/AbstractCommand.php, src/Command/Build.php, src/Command/Clear.php, src/Command/Serve.php
Removed baseurl replacement logic from router.php and updated Serve.php to pass baseurl and output directory as arguments instead of using a temporary baseurl file. This simplifies local server setup and improves configuration clarity.
=> refactor: serve command and router baseurl handling
